### ISSUE TITLE
맥주 검색 결과 페이지에서 맥주 사진이 안보임 🥲

### ISSUE THREAD

**Issue by ddarkr** [depromeet/sulsul-FE#169]
안녕하세요~ 예쁜 디자인과 멋진 서비스가 런칭했다는 소식에 써보려고 달려갔는데... 🏃

![image](https://user-images.githubusercontent.com/6638675/175485707-e951b6e6-27fb-4e13-8108-f21f2e6aec04.png)

-webkit-mask-image 처리에 사용된 이미지가 CORS로 인해 로딩되지 못하면서 맥주 이미지가 안나옵니다 ㅠㅠ

![image](https://user-images.githubusercontent.com/6638675/175485678-2ca57c65-ca37-4cc7-b730-5b2ba04ecd00.png)

![image](https://user-images.githubusercontent.com/6638675/175485732-49fcffc5-f6be-4736-b8c6-0877343c2892.png)

**Comment by hy57in** [comment]
앗 소중한 제보 감사합니다! mask-image는 더 이상 사용하지 않는 기능이라 제거하도록 하겠습니다
조금만 기다려주세요 ~!~!
