### ISSUE TITLE
PC에서 다음 버튼이 안보여요 

### ISSUE THREAD

**Issue by wurikiji** [depromeet/sulsul-FE#170]
# Actual result

![image](https://user-images.githubusercontent.com/5652744/175605461-db6498de-2459-4cd2-b9a0-bb93f2e2e4e6.png)

# Expected

![image](https://user-images.githubusercontent.com/5652744/175605639-a00fef2e-906f-4551-9c9f-9849f5341261.png)

**Comment by hy57in** [comment]
모바일first 로 대응을 하다보니 태블릿 크기일 땐 미처 대응을 하지 못했네요 ㅠㅠ
반응형도 챙겨보겠습니다!
