### ISSUE TITLE
qa 투척! 15자 이상 입력 시, 텍스트 지우기가 안됩니다..ㅎㅎ

### ISSUE THREAD

**Issue by hy57in** [depromeet/sulsul-FE#184]
![D24904B7-9A90-4724-9D68-2714AFCEEC7A](https://user-images.githubusercontent.com/60775453/175759222-3677416a-d686-4275-89d0-c7a3155060a1.jpeg)

**Comment by cyjo9603** [comment]
https://github.com/depromeet/sulsul-FE/pull/194
