### ISSUE TITLE
응답에서는 isLiked가 true인데, 새로고침 마다 가끔 목록화면에 좋아요 정보가 반영이 안되어 있는 경우(false)가 있습니다

### ISSUE THREAD

**Issue by hy57in** [depromeet/sulsul-FE#187]
<img width="1718" alt="KakaoTalk_Photo_2022-06-25-21-43-27" src="https://user-images.githubusercontent.com/60775453/175774011-0b22dbea-51be-4d4c-91c7-7a74ff2c22e4.png">
요건 FE 이슈인 것 같기도 한데요! 
응답에서는 isLiked가 true인데, 새로고침 마다 가끔 목록화면에 좋아요 정보가 반영이 안되어 있는 경우(false)가 있습니다

**Comment by syoung125** [comment]
https://tkdodo.eu/blog/effective-react-query-keys#structure
요거 참고해서 수정
